spring.application.name=inventory

spring.jackson.property-naming-strategy=SNAKE_CASE
spring.jackson.deserialization.accept-empty-string-as-null-object=true

spring.datasource.url=jdbc:sqlite:../db/inventory.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-init-sql=PRAGMA foreign_keys=ON

spring.sql.init.mode=always

springdoc.packages-to-scan=com.coding.challenge.inventory.api
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.tags-sorter=alpha
